FROM nvidia/cuda:12.9.0-base-ubuntu22.04

USER root

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    python3 \
    python3-venv \
    python3-pip \
    curl \
    wget \
    git \
    neovim \
    nano \
    unzip \
    ranger \
    zip \
    git-lfs \
    make \
    xdg-utils \
    language-pack-en-base \
    nvidia-driver-535 \
    nvidia-dkms-535 \
    libopenblas-dev

RUN apt-get install -y

ADD --chmod=755 https://astral.sh/uv/install.sh /install.sh
RUN /install.sh && rm /install.sh

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash
